### ISSUE TITLE
Applications to financial industry or NLP

### ISSUE THREAD

**Issue by datatalking** [aangelopoulos/rcps#1]
I read your fantastic paper on [A Gentle Introduction to Conformal Prediction and Distribution-Free Uncertainty Quantification](https://arxiv.org/pdf/2107.07511.pdf) and wanted to ask about the application of it to industries. There seems to be applications for multiple markets, the potential looks impressive but I'm still trying to wrap my head around implementation or integration perhaps. In section 2.3 figure 6 does a great job of explaining what it does and in section 2.4 Conformalizing Bayes you talk about priors.

As far as implementation you show more examples of image classification and image processing in the [conformal_classifcation GitHub repo](https://github.com/aangelopoulos/conformal_classification), but many of your videos I believe mention this in application of the stock market and risk assessment. Can you clarify, also if this isn't the place for these questions let me know where is appropriate.

I'm researching using something like your method for my work in NLP or hobby algorithmic financial risk assessment but there are many questions your great paper solved and a few more it created.

**Comment by aangelopoulos** [comment]
Hi!

  I think that there are some recent time-series papers that might be relevant to stock market/risk assessment. These include http://proceedings.mlr.press/v139/xu21h/xu21h.pdf https://hal.archives-ouvertes.fr/hal-03573934/file/AdaptiveConformalPredictionsTimeSeries.pdf https://arxiv.org/abs/2205.09095 https://arxiv.org/abs/2202.13415

  Hopefully you find these references helpful!  I have yet to put them in the gentle intro, but will soon :)

Best,
Anastasios

**Comment by datatalking** [comment]
@aangelopoulos I've been reviewing those links you sent. So this repo is more for image classification and processing, but would you say its better at identifying printed text or would it also work for hand written? Perhaps this is a question of classification given resolution is >= x dots per inch or?

**Comment by aangelopoulos** [comment]
This repo has examples in image classification, image segmentation, and protein folding. However the statistical technique of RCPS is equally applicable to any problem setup, including printed text or handwritten text classification. It also works outside the framework of image classification and processing! You may want to review the arXiv posting here to learn more: https://arxiv.org/abs/2101.02703
